Web2Project/Controllers/MojNalogController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Web2Project.Helper;
using Web2Project.Models;
using Web2Project.Services;

namespace Web2Project.Controllers
{
    public class MojNalogController : Controller
    {
        IUserRepository _userRepository;
        IFileUploadService _fileUploadService;

        public MojNalogController(IUserRepository userRepository, IFileUploadService fileUploadService)
        {
            _userRepository = userRepository;
            _fileUploadService = fileUploadService;
        }

        public IActionResult Index()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("UlogovanKorisnik")))
            {
                return RedirectToAction("Index", "Authentication");
            }
            else
            {
                Korisnik korisnik = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("UlogovanKorisnik"));

                if (korisnik == null)
                {
                    return RedirectToAction("Index", "Authentication");
                }
            }

            string message = HttpContext.Session.GetString("AlertMessage");
            if (message != "" && message != null)
            {
                ViewBag.AlertMessage = message;
                ViewBag.Uspesno = JsonConvert.DeserializeObject<bool>(HttpContext.Session.GetString("Uspesno"));

                HttpContext.Session.SetString("AlertMessage", "");
            }

            ViewBag.korisnik = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("UlogovanKorisnik"));
            return View();
        }

        public ActionResult LicniPodaci()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("UlogovanKorisnik")))
            {
                return RedirectToAction("Index", "Authentication");
            }
            else
            {
                Korisnik korisnik = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("UlogovanKorisnik"));

                if (korisnik == null)
                {
                    return RedirectToAction("Index", "Authentication");
                }
            }

            string message = HttpContext.Session.GetString("AlertMessage");
            if (message != "" && message != null)
            {
                ViewBag.AlertMessage = message;
                ViewBag.Uspesno = JsonConvert.DeserializeObject<bool>(HttpContext.Session.GetString("Uspesno"));

                HttpContext.Session.SetString("AlertMessage", "");
            }

            ViewBag.korisnik = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("UlogovanKorisnik"));
            ViewBag.Message = "";

            return View();
        }

        [HttpPost]
        public ActionResult LicniPodaciPromenjeni(string korisnickoime, string ime, string prezime, string adresa, IFormFile ifile, DateTime DatumRodjenja)
        {
            Korisnik korisnik = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("UlogovanKorisnik"));

            bool flag = false;

            if (korisnickoime != "" || ime != "" || prezime != "" || adresa != "" || ifile !=null || !DatumRodjenja.ToString().Contains("01-Jan-01"))
            {
                if (ime != null && ime != "" && ime != korisnik.Ime)
                {
                    korisnik.Ime = ime;
                    flag = true;

                    _userRepository.UpdateKorisnik(korisnik, "Ime", ime);
                }
                if (prezime != null && prezime != "" && prezime != korisnik.Prezime)
                {
                    korisnik.Prezime = prezime;
                    flag = true;

                    _userRepository.UpdateKorisnik(korisnik, "Prezime", prezime);
                }
                if (adresa != null && adresa != "" && korisnik.Adresa != adresa)
                {
                    korisnik.Adresa = adresa;
                    flag = true;

                    _userRepository.UpdateKorisnik(korisnik, "Adresa", adresa);
                }
                if(ifile != null)
                {
                    string imgext = Path.GetExtension(ifile.FileName).ToLower();
                    if (imgext != ".jpg" && imgext != ".png")
                    {
                        HttpContext.Session.SetString("AlertMessage", "Slika mora biti u .jpg ili .png formatu!");
                        HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(false));

                        return RedirectToAction("LicniPodaci");
                    }

                    flag = true;
                    _fileUploadService.UploadFile(ifile, korisnik.Id.ToString(), "Korisnici");

                    if (korisnik.ImagePath.Contains("unknown.jpg"))
                    {
                        korisnik.ImagePath = "~/Korisnici/" + korisnik.Id + ".jpg";
                        _userRepository.UpdateKorisnik(korisnik, "ImagePath", korisnik.ImagePath);
                    }
                }
                if (!DatumRodjenja.ToString().Contains("01-Jan-01") && DatumRodjenja > DateTime.Now)
                {
                    flag = true;
                    korisnik.DatumRodjenja = DatumRodjenja;

                    _userRepository.UpdateKorisnik(korisnik, "DatumRodjenja", korisnik.DatumRodjenja.ToString());
                }

                if (korisnickoime != null && korisnickoime != "" && korisnickoime != korisnik.KorisnickoIme)
                {
                    if (_userRepository.Existing(korisnickoime))
                    {
                        HttpContext.Session.SetString("AlertMessage", "Korisnicko ime je zauzeto");
                        HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(false));

                        return RedirectToAction("LicniPodaci");
                    }
                    else
                    {
                        korisnik.KorisnickoIme = korisnickoime;
                        flag = true;

                        _userRepository.UpdateKorisnik(korisnik, "KorisnickoIme", korisnickoime);
                    }
                }
            }

            if (flag)
            {
                HttpContext.Session.SetString("AlertMessage", "Licni podaci uspesno izmenjeni!");
                HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(true));

                HttpContext.Session.SetString("UlogovanKorisnik", JsonConvert.SerializeObject(korisnik));
            }
            else
            {
                HttpContext.Session.SetString("AlertMessage", "Licni podaci nisu izmenjeni!");
                HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(false));
            }

            return RedirectToAction("Index");
        }

        public ActionResult Email()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("UlogovanKorisnik")))
            {
                return RedirectToAction("Index", "Authentication");
            }
            else
            {
                Korisnik korisnik = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("UlogovanKorisnik"));

                if (korisnik == null)
                {
                    return RedirectToAction("Index", "Authentication");
                }
            }

            string message = HttpContext.Session.GetString("AlertMessage");
            if (message != "" && message != null)
            {
                ViewBag.AlertMessage = message;
                ViewBag.Uspesno = JsonConvert.DeserializeObject<bool>(HttpContext.Session.GetString("Uspesno"));

                HttpContext.Session.SetString("AlertMessage", "");
            }

            ViewBag.korisnik = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("UlogovanKorisnik"));

            return View();
        }

        [HttpPost]
        public ActionResult EmailPromenjen(string email, string lozinka)
        {
            Korisnik korisnik = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("UlogovanKorisnik"));

            if (email != null && email != "" && email != korisnik.Email)
            {
                bool isEmail = Regex.IsMatch(email, @"\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z", RegexOptions.IgnoreCase);

                lozinka = Operations.hashPassword(lozinka);

                if (lozinka == korisnik.Lozinka && isEmail)
                {
                    korisnik.Email = email;
                    _userRepository.UpdateKorisnik(korisnik, "Email", email);

                    HttpContext.Session.SetString("AlertMessage", "Email uspesno izmenjen!");
                    HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(true));

                    HttpContext.Session.SetString("UlogovanKorisnik", JsonConvert.SerializeObject(korisnik));
                }
                else
                {
                    if (!isEmail)
                    {
                        HttpContext.Session.SetString("AlertMessage", "Email nije validan!");
                        HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(false));
                    }

                    if (lozinka != korisnik.Lozinka)
                    {
                        HttpContext.Session.SetString("AlertMessage", "Neispravna lozinka!");
                        HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(false));
                    }

                    ViewBag.korisnik = korisnik;
                    return RedirectToAction("Email");
                }
            }

Web2Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web2Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Authentication" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (ViewBag.korisnik.LogedIn)
                        {
                            @if (ViewBag.korisnik.Verifikovan == Zahtev.PRIHVACEN)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="MojNalog" asp-action="Index">Moj Nalog</a>
                                </li>

                            }
                            @if (ViewBag.korisnik.TipKorisnika == Tip.ADMINISTRATOR)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Administrator" asp-action="Proizvodi">Proizvodi</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Administrator" asp-action="Kategorije">Kategorije</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Administrator" asp-action="Verifikuj">Verifikuj dostavljace</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Administrator" asp-action="SvePorudzbine">Sve porudzbine</a>
                                </li>
                                <li class="nav-item offset-4">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Logout">Odjavi se</a>
                                </li>
                            }
                            else if (ViewBag.korisnik.TipKorisnika == Tip.DOSTAVLJAC)
                            {
                                if (ViewBag.korisnik.Verifikovan == Zahtev.PRIHVACEN)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Dostavljac" asp-action="NovePorudzbine">Nove porudzbine</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Dostavljac" asp-action="MojePorudzbine">Moje porudzbine</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Dostavljac" asp-action="TrenutnaPorudzbina">Trenutna porudzbina</a>
                                    </li>
                                    <li class="nav-item offset-4">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Logout">Odjavi se</a>
                                    </li>
                                }
                                else
                                {
                                    <li class="nav-item offset-11">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Logout">Odjavi se</a>
                                    </li>
                                }
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Potrosac" asp-action="NovaPorudzbina">Nova porudzbina</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Potrosac" asp-action="MojaKorpa">Moja korpa</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Potrosac" asp-action="MojePorudzbine">Moje porudzbine</a>
                                </li>
                                <li class="nav-item offset-5">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Logout">Odjavi se</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2022 - Web2Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>