Web2Project/Controllers/AdministratorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Web2Project.Helper;
using Web2Project.Models;
using Web2Project.Services;

namespace Web2Project.Controllers
{
    public class AdministratorController : Controller
    {
        IProductRepository _productRepository;
        ICategoryRepository _categoryRepository;
        IUserRepository _userRepository;
        IEmailSender _emailSender;
        IFileUploadService _fileUploadService;
        IBasketRepository _basketRepository;
        IBasketProductRepository _basketProductRepository;

        public AdministratorController(IProductRepository productRepository, ICategoryRepository categoryRepository, IUserRepository userRepository, IEmailSender emailSender, IFileUploadService fileUploadService, IBasketRepository basketRepository, IBasketProductRepository basketProductRepository)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
            _userRepository = userRepository;
            _emailSender = emailSender;
            _fileUploadService = fileUploadService;
            _basketRepository = basketRepository;
            _basketProductRepository = basketProductRepository;
        }

        public IActionResult Index()
        {
            Korisnik administrator = new Korisnik();

            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UlogovanKorisnik")))
            {
                administrator = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("UlogovanKorisnik"));

                if (administrator == null)
                {
                    return RedirectToAction("Index", "Authentication");
                }
                else
                {
                    if (administrator.TipKorisnika == Tip.POTROSAC)
                    {
                        return RedirectToAction("Index", "Potrosac");
                    }
                    else if (administrator.TipKorisnika == Tip.DOSTAVLJAC)
                    {
                        return RedirectToAction("Index", "Dostavljac");
                    }
                }
            }
            else
            {
                return RedirectToAction("Index", "Authentication");
            }

            string message = HttpContext.Session.GetString("AlertMessage");
            if (message != "" && message != null)
            {
                ViewBag.AlertMessage = message;
                ViewBag.Uspesno = JsonConvert.DeserializeObject<bool>(HttpContext.Session.GetString("Uspesno"));

                HttpContext.Session.SetString("AlertMessage", "");
            }

            ViewBag.korisnik = administrator;
            return View();
        }


        
        public IActionResult Proizvodi()
        {
            Korisnik administrator = new Korisnik();

            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UlogovanKorisnik")))
            {
                administrator = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("UlogovanKorisnik"));

                if (administrator == null)
                {
                    return RedirectToAction("Index", "Authentication");
                }
                else
                {
                    if (administrator.TipKorisnika == Tip.POTROSAC)
                    {
                        return RedirectToAction("Index", "Potrosac");
                    }
                    else if (administrator.TipKorisnika == Tip.DOSTAVLJAC)
                    {
                        return RedirectToAction("Index", "Dostavljac");
                    }
                }
            }
            else
            {
                return RedirectToAction("Index", "Authentication");
            }

            ViewBag.korisnik = administrator;

            List<Proizvod> proizvodi = _productRepository.GetAllProduct();
            proizvodi = proizvodi.OrderBy(p => p.KategorijaId).ToList();
            ViewBag.Proizvodi = proizvodi;

            string message = HttpContext.Session.GetString("AlertMessage");
            if (message != "" && message != null)
            {
                ViewBag.AlertMessage = message;
                ViewBag.Uspesno = JsonConvert.DeserializeObject<bool>(HttpContext.Session.GetString("Uspesno"));

                HttpContext.Session.SetString("AlertMessage", "");
            }

            return View();
        }
   
        public IActionResult DodajProizvod()
        {
            Korisnik administrator = new Korisnik();

            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UlogovanKorisnik")))
            {
                administrator = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("UlogovanKorisnik"));

                if (administrator == null)
                {
                    return RedirectToAction("Index", "Authentication");
                }
                else
                {
                    if (administrator.TipKorisnika == Tip.POTROSAC)
                    {
                        return RedirectToAction("Index", "Potrosac");
                    }
                    else if (administrator.TipKorisnika == Tip.DOSTAVLJAC)
                    {
                        return RedirectToAction("Index", "Dostavljac");
                    }
                }
            }
            else
            {
                return RedirectToAction("Index", "Authentication");
            }
            ViewBag.kategorije = _categoryRepository.GetAll();
            ViewBag.korisnik = administrator;

            string message = HttpContext.Session.GetString("AlertMessage");
            if (message != "" && message != null)
            {
                ViewBag.AlertMessage = message;
                ViewBag.Uspesno = JsonConvert.DeserializeObject<bool>(HttpContext.Session.GetString("Uspesno"));

                HttpContext.Session.SetString("AlertMessage", "");
            }

            return View();
        }

        [HttpPost]
        public IActionResult ProizvodDodat(Proizvod proizvod, IFormFile ifile)
        {
            Korisnik administrator = new Korisnik();

            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UlogovanKorisnik")))
            {
                administrator = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("UlogovanKorisnik"));

                if (administrator == null)
                {
                    return RedirectToAction("Index", "Authentication");
                }
                else
                {
                    if (administrator.TipKorisnika == Tip.POTROSAC)
                    {
                        return RedirectToAction("Index", "Potrosac");
                    }
                    else if (administrator.TipKorisnika == Tip.DOSTAVLJAC)
                    {
                        return RedirectToAction("Index", "Dostavljac");
                    }
                }
            }
            else
            {
                return RedirectToAction("Index", "Authentication");
            }

            if (proizvod.Naziv == null || proizvod.Naziv == "" || proizvod.Sastojci == null || proizvod.Sastojci == "" || proizvod.Cena < 1)
            {
                HttpContext.Session.SetString("AlertMessage", "Sva polja moraju biti pravilno popunjena!");
                HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(false));

                return RedirectToAction("DodajProizvod");
            }

            if (_productRepository.Existing(proizvod.Naziv))
            {
                HttpContext.Session.SetString("AlertMessage", "Proizvod sa ovim nazivom vec postoji!");
                HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(false));

                return RedirectToAction("DodajProizvod");
            }

            if (ifile != null)
            {
                string imgext = Path.GetExtension(ifile.FileName).ToLower();
                if (imgext != ".jpg" && imgext != ".png")
                {
                    HttpContext.Session.SetString("AlertMessage", "Slika mora biti u .jpg ili .png formatu!");
                    HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(false));

                    return RedirectToAction("DodajProizvod");
                }
            }
            _productRepository.Add(proizvod);

            string imagePath = "";

            if (ifile != null)
            {
                _fileUploadService.UploadFile(ifile, proizvod.Id.ToString(), "Proizvodi");
                imagePath = "~/Proizvodi/" + proizvod.Id + ".jpg";
            }
            else
            {
                imagePath = "~/Proizvodi/unknown.jpg";
            }

            _productRepository.UpdateProperty(proizvod, "ImagePath", imagePath);

            HttpContext.Session.SetString("AlertMessage", "Novi proizvod uspesno dodat!");
            HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(true));

            return RedirectToAction("Proizvodi");
        }

        public IActionResult ObrisiProizvod(int id)
        {
            Korisnik administrator = new Korisnik();

            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UlogovanKorisnik")))
            {
                administrator = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("UlogovanKorisnik"));

                if (administrator == null)
                {
                    return RedirectToAction("Index", "Authentication");
                }
                else
                {
                    if (administrator.TipKorisnika == Tip.POTROSAC)
                    {
                        return RedirectToAction("Index", "Potrosac");
                    }

Web2Project/Views/Administrator/DodajKategoriju.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Dodaj kategoriju</title>
    <style>
        div.row {
            display: flex;
            align-items: center;
        }
    </style>
    <script>

        var username = true;
        function NazivEmpty() {
            if ($("#Naziv").val() == "") {

                    $("#Status1").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                    $("#Naziv").css("border-color", "Red");

            }else{
                    $.post("@Url.Action("CheckCategoryAvailability", "Administrator")",
                    {
                        userdata: $("#Naziv").val()
                    },
                    function (data) {
                        if (data == 0) {
                            $("#Status1").html('');
                            $("#Naziv").css("border-color", "lightgray");
                            username = true;
                        } else {
                            $("#Status1").html('<font color="Red">Kategorija sa ovim nazivom vec postoji!</font>');
                            $("#Naziv").css("border-color", "Red");
                            username = false;  
                        }
                    });
            }
        }

        function validateForm() {
            var dobro = true;

            if ($("#Naziv").val() == "") {
                $("#Status1").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                $("#Naziv").css("border-color", "Red");
                dobro = false;
            } else if (username) {
                $("#Status1").html('');
                $("#Naziv").css("border-color", "lightgray");
            }

            return dobro && username;
        }
    </script>
</head>
<body>
    @if (ViewBag.AlertMessage != null)
    {
        if (ViewBag.Uspesno)
        {
            <script type="text/javascript">
                    window.onload = function () {
                        toastr.success("@ViewBag.AlertMessage");
                    };
            </script>
        }
        else
        {
            <script type="text/javascript">
                    window.onload = function () {
                        toastr.error("@ViewBag.AlertMessage");
                    };
            </script>
        }
    }
    <div class="col-6">
        <h2 class="text-info">Dodajte novu kategoriju:</h2>
    </div>
    <br />
    <form method="post" action="~/Administrator/KategorijaDodata" onsubmit="return validateForm()">
        <div class="form-group">
            <div class="row">
                <label class="control-label col-sm-2">Naziv:</label>
                <div class="col-sm-3">
                    <input class="form-control" type="text" placeholder="Unesite naziv kategorije" maxlength="30" id="Naziv" name="Naziv" onchange="NazivEmpty()" />
                </div>
                <label class="col-sm-4" id="Status1"></label>
            </div>
            <br />
            <div class="row">
                <div class="col-sm-4">
                    <input class="btn btn-primary" type="submit" value="Dodaj" />
                </div>
            </div>
        </div>
    </form>
</body>
</html>

Web2Project/Views/Administrator/DodajProizvod.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Dodaj proizvod</title>
    <style>
        div.row {
            display: flex;
            align-items: center;
        }
    </style>
    <script>
        var naziv = true;

        function NazivEmpty() {
            if ($("#Naziv").val() == "") {
                $("#Status1").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#Naziv").css("border-color", "Red");
            } else {
                $.post("@Url.Action("CheckProductAvailability", "Administrator")",
                {
                    userdata: $("#Naziv").val()
                },
                function (data) {
                    if (data == 0) {
                        $("#Status1").html('<font color="Green"></font>');
                        $("#Naziv").css("border-color", "GreenYellow");
                        naziv = true;
                    } else {
                        $("#Status1").html('<font color="Red">Proizvod sa ovim nazivom vec postoji!</font>');
                        $("#Naziv").css("border-color", "Red");
                        naziv = false;
                    }
                });
            }
        }

        function CenaEmpty() {
            if ($("#Cena").val() == "") {
                $("#Status2").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#Cena").css("border-color", "Red");
            } else {
                $("#Status2").html('');
                $("#Cena").css("border-color", "lightgray");
            }
        }
        function SastojciEmpty() {
            if ($("#Sastojci").val() == "") {
                $("#Status3").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                $("#Sastojci").css("border-color", "Red");
            } else {
                $("#Status3").html('');
                $("#Sastojci").css("border-color", "lightgray");
            }
        }

        function validateForm() {
            var dobro = true;

            if ($("#Naziv").val() == "") {
                $("#Status1").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                $("#Naziv").css("border-color", "Red");
                dobro = false;
            } else if (naziv) {
                $("#Status1").html('');
                $("#Naziv").css("border-color", "GreenYellow");
            }
            if ($("#Cena").val() == "") {
                $("#Status2").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                $("#Cena").css("border-color", "Red");
                dobro = false;
            } else {
                $("#Status2").html('');
                $("#Cena").css("border-color", "lightgray");
            }
            if ($("#Sastojci").val() == "") {
                $("#Status3").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                $("#Sastojci").css("border-color", "Red");
                dobro = false;
            } else {
                $("#Status3").html('');
                $("#Sastojci").css("border-color", "lightgray");
            }

            return dobro && naziv;
        }
    </script>
</head>
<body>
    @if (ViewBag.AlertMessage != null)
    {
        if (ViewBag.Uspesno)
        {
            <script type="text/javascript">
                    window.onload = function () {
                        toastr.success("@ViewBag.AlertMessage");
                    };
            </script>
        }
        else
        {
            <script type="text/javascript">
                    window.onload = function () {
                        toastr.error("@ViewBag.AlertMessage");
                    };
            </script>
        }
    }
    <h2 class="text-info">Dodajte novi proizvod:</h2>
    <br />
    <form method="post" action="~/Administrator/ProizvodDodat" enctype="multipart/form-data" onsubmit="return validateForm()">
        <div class="form-group">
            <div class="row">
                <label class="control-label col-sm-2">Ime:</label>
                <div class="col-sm-3">
                    <input class="form-control" type="text" placeholder="Unesite ime proizvoda" maxlength="30" id="Naziv" name="Naziv" onchange="NazivEmpty()" />
                </div>
                <label class="col-sm-4" id="Status1"></label>
            </div>
            <br />
            <div class="row">
                <label class="control-label col-sm-2">Cena:</label>
                <div class="col-sm-3">
                    <input class="form-control" type="number" placeholder="Unesite cenu proizvoda" min="1" max="1000000" id="Cena" name="Cena" onchange="CenaEmpty()" />
                </div>
                <label class="col-sm-4" id="Status2"></label>
            </div>
            <br />
            <div class="row">
                <label class="control-label col-sm-2">Sastojci:</label>
                <div class="col-sm-3">
                    <textarea class="form-control" name="Sastojci" id="Sastojci" onchange="SastojciEmpty()" style="font-family:sans-serif;font-size:1.2em;"></textarea>
                </div>
                <label class="col-sm-4" id="Status3"></label>
            </div>
            <br />
            <div class="row">
                <label class="control-label col-sm-2">Kategorija:</label>
                <div class="col-sm-3">
                    <select class="form-control" name="KategorijaId" id="KategorijaId">
                        @foreach (var k in @ViewBag.kategorije)
                        {
                            <option value="@k.Id">@k.Naziv</option>

                        }
                    </select>
                </div>
            </div>
            <br />
            <div class="row">
                <label class="control-label col-sm-2">Slika:</label>
                <div class="col-sm-3">
                    <input type="file" name="ifile" />
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-sm-4">
                    <input class="btn btn-primary" type="submit" value="Dodaj" />
                </div>
            </div>
        </div>
    </form>
</body>
</html>

Web2Project/Views/Administrator/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Home</title>
    </head>
    <body>
        @if (ViewBag.AlertMessage != null)
        {
            if (ViewBag.Uspesno)
            {
                <script type="text/javascript">
                    window.onload = function () {
                        toastr.success("@ViewBag.AlertMessage");
                    };
                </script>
            }
            else
            {
                <script type="text/javascript">
                    window.onload = function () {
                        toastr.error("@ViewBag.AlertMessage");
                    };
                </script>
            }
        }

    <label>@ViewBag.korisnik.KorisnickoIme uspesno ulogovan!</label>
    </body>
</html>

Web2Project/Views/Administrator/IzmeniKategoriju.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Dodaj kategoriju</title>
    <style>
        div.row {
            display: flex;
            align-items: center;
        }
    </style>
    <script>

        var username = true;
        function NazivEmpty() {
            if ($("#Naziv").val() == "") {

                    $("#Status1").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                    $("#Naziv").css("border-color", "Red");

            }else{
                    $.post("@Url.Action("CheckCategoryAvailability", "Administrator")",
                    {
                        userdata: $("#Naziv").val()
                    },
                    function (data) {
                        if (data == 0) {
                            $("#Status1").html('');
                            $("#Naziv").css("border-color", "lightgray");
                            username = true;
                        } else {
                            $("#Status1").html('<font color="Red">Kategorija sa ovim nazivom vec postoji!</font>');
                            $("#Naziv").css("border-color", "Red");
                            username = false;
                        }
                    });
            }
        }

        function validateForm() {
            var dobro = true;

            if ($("#Naziv").val() == "") {
                $("#Status1").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                $("#Naziv").css("border-color", "Red");
                dobro = false;
            } else if (username) {
                $("#Status1").html('');
                $("#Naziv").css("border-color", "lightgray");
            }

            return dobro && username;
        }
    </script>
</head>
<body>
    <h2>Dodajte novu kategoriju:</h2>
    <br />
    <form method="post" action="~/Administrator/KategorijaIzmenjena?id=@ViewBag.Id" onsubmit="return validateForm()">
        <div class="form-group">
            <div class="row">
                <label class="control-label col-sm-2">Novi naziv:</label>
                <div class="col-sm-3">
                    <input class="form-control" type="text" placeholder="Unesite novi naziv kategorije" maxlength="30" id="Naziv" name="Naziv" onchange="NazivEmpty()" />
                </div>
                <label class="col-sm-4" id="Status1"></label>
            </div>
            <br />
            <div class="row">
                <div class="col-sm-4">
                    <input class="btn btn-primary" type="submit" value="Izmeni" />
                </div>
            </div>
        </div>
    </form>
</body>
</html>

Web2Project/Views/Administrator/IzmeniProizvod.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Izmeni proizvoid</title>
        <style>
        div.row {
            display: flex;
            align-items: center;
        }
        </style>
        <script>
            function NameCheck() {
                if ($("#Naziv").val() != "") {
                    $.post("@Url.Action("CheckProductAvailability", "Administrator")",
                        {
                            userdata: $("#Naziv").val()
                        },
                        function (data) {
                            if (data == 0) {
                                $("#Status1").html('<font color="Green"></font>');
                                $("#Naziv").css("border-color", "GreenYellow");
                                naziv = true;
                            } else {
                                $("#Status1").html('<font color="Red">Proizvod sa ovim nazivom vec postoji!</font>');
                                $("#Naziv").css("border-color", "Red");
                                naziv = false;
                            }
                        });

                    return naziv;
                } else {
                    $("#Naziv").css("border-color", "lightgray");
                }
            }



        </script>
    </head>
    <body>
        @if (ViewBag.AlertMessage != null)
        {
            if (ViewBag.Uspesno)
            {
                <script type="text/javascript">
                    window.onload = function () {
                        toastr.success("@ViewBag.AlertMessage");
                    };
                </script>
            }
            else
            {
                <script type="text/javascript">
                    window.onload = function () {
                        toastr.error("@ViewBag.AlertMessage");
                    };
                </script>
            }
        }
        <br /><br />
        <div class="col-12 border p-3">
            <table class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr align="center">
                        <th>Naziv</th>
                        <th>Cena</th>
                        <th>Sastojci</th>
                        <th>Kategorija</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td align="center">@ViewBag.Proizvod.Naziv</td>
                        <td align="center">@ViewBag.Proizvod.Cena</td>
                        <td align="center">@ViewBag.Proizvod.Sastojci</td>
                        <td align="center">@ViewBag.Kategorija.Naziv</td>
                        <td align="center"><img src="@ViewBag.Proizvod.ImagePath" height="100" width="100" asp-append-version="true" /></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <br /><br />
        <h2 class="text-info">Izmenite proizvod:</h2>
        <br />
        <form method="post" action="~/Administrator/ProizvodIzmenjen?id=@ViewBag.Proizvod.Id" enctype="multipart/form-data" onsubmit="return NameCheck()">
            <div class="form-group">
                <div class="row">
                    <label class="control-label col-sm-2">Izmeni ime:</label>
                    <div class="col-sm-3">
                        <input class="form-control" placeholder="Unesite novo ime proizvoda" type="text" id="Naziv" onchange="NameCheck()" name="Naziv" />
                    </div>
                    <label class="col-sm-4" id="Status1"></label>
                </div>
                <br />
                <div class="row">
                    <label class="control-label col-sm-2">Izmeni cenu:</label>
                    <div class="col-sm-3">
                        <input class="form-control" placeholder="Unesite novu cenu proizvoda" type="number" min="1" max="1000000" id="Cena" name="Cena" />
                    </div>
                </div>
                <br />
                <div class="row">
                    <label class="control-label col-sm-2">Izmeni sastojke:</label>
                    <div class="col-sm-3">
                        <input class="form-control" placeholder="Unesite nove sastojke proizvoda" type="text" id="Sastojci" name="Sastojci" />
                    </div>
                </div>
                <br />
                <div class="row">
                    <label class="control-label col-sm-2">Izmeni kategoriju:</label>
                    <div class="col-sm-3">
                        <input class="form-control" list="kategorije" placeholder="Promenite kategoriju" name="KategorijaId" id="KategorijaId" />
                        <datalist id="kategorije">
                            @foreach (var item in ViewBag.kategorije)
                            {
                                <option value="@item.Id">@item.Naziv</option>
                            }
                        </datalist>
                    </div>
                </div>
                <br />
                <div class="row">
                    <label class="control-label col-sm-2">Izmeni sliku:</label>
                    <div class="col-sm-3">
                        <input type="file" name="ifile" />
                    </div>
                </div>
                <br />
                <div class="row">
                    <input class="btn btn-primary" type="submit" value="Sacuvaj izmene" />
                </div>
            </div>
        </form>
    </body>
</html>