Web2Project/Controllers/DostavljacController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web2Project.Helper;
using Web2Project.Models;

namespace Web2Project.Controllers
{
    public class DostavljacController : Controller
    {
        IProductRepository _productRepository;
        IBasketRepository _basketRepository;
        IBasketProductRepository _basketProductRepository;
        IUserRepository _userRepository;

        public DostavljacController(IProductRepository productRepository, IBasketRepository basketRepository, IBasketProductRepository basketProductRepository, IUserRepository userRepository)
        {
            _productRepository = productRepository;
            _basketRepository = basketRepository;
            _basketProductRepository = basketProductRepository;
            _userRepository = userRepository;
        }

        public IActionResult Index()
        {
            Korisnik dostavljac = new Korisnik();

            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UlogovanKorisnik")))
            {
                dostavljac = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("UlogovanKorisnik"));

                if (dostavljac == null)
                {
                    return RedirectToAction("Index", "Authentication");
                }
                else
                {
                    if (dostavljac.TipKorisnika == Tip.ADMINISTRATOR)
                    {
                        return RedirectToAction("Index", "Administrator");
                    }
                    else if(dostavljac.TipKorisnika == Tip.POTROSAC)
                    {
                        return RedirectToAction("Index", "Potrosac");
                    }
                }
            }
            else
            {
                return RedirectToAction("Index", "Authentication");
            }

            string message = HttpContext.Session.GetString("AlertMessage");
            if (message != "" && message != null)
            {
                ViewBag.AlertMessage = message;
                ViewBag.Uspesno = JsonConvert.DeserializeObject<bool>(HttpContext.Session.GetString("Uspesno"));

                HttpContext.Session.SetString("AlertMessage", "");
            }

            ViewBag.korisnik = dostavljac;
            return View();
        }

        public IActionResult NovePorudzbine()
        {
            Korisnik dostavljac = new Korisnik();

            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UlogovanKorisnik")))
            {
                dostavljac = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("UlogovanKorisnik"));

                if (dostavljac == null)
                {
                    return RedirectToAction("Index", "Authentication");
                }
                else
                {
                    if (dostavljac.TipKorisnika == Tip.ADMINISTRATOR)
                    {
                        return RedirectToAction("Index", "Administrator");
                    }
                    else if (dostavljac.TipKorisnika == Tip.POTROSAC)
                    {
                        return RedirectToAction("Index", "Potrosac");
                    }
                }
            }
            else
            {
                return RedirectToAction("Index", "Authentication");
            }
            ViewBag.korisnik = dostavljac;

            Korpa aktivna = _basketRepository.GetDostavljacActiveBasket(dostavljac.Id);

            if(aktivna != null)
                return RedirectToAction("TrenutnaPorudzbina");
            

            List<Korpa> porudzbine = _basketRepository.GetDostavljacBasket();

            Dictionary<int, float> cene = new Dictionary<int, float>();
            Dictionary<int, Korisnik> primaoci = new Dictionary<int, Korisnik>();

            List<Stavka> stavke = new List<Stavka>();

            foreach (var p in porudzbine)
            {
                cene.Add(p.Id, p.Cena - 400);
                
                List<KorpaProizvod> proizvodi = _basketProductRepository.GetAllProducts(p.Id);

                Korisnik primalac = _userRepository.Get(p.KorisnikId);
                primaoci.Add(p.Id, primalac);

                foreach (var item in proizvodi)
                {
                    Stavka stavka = new Stavka();
                    stavka.KorpaId = p.Id;

                    stavka.Proizvod = _productRepository.Get(item.ProizvodId);
                    stavka.Kolicina = item.Kolicina;

                    stavke.Add(stavka);
                }
            }

            string message = HttpContext.Session.GetString("AlertMessage");
            if (message != "" && message != null)
            {
                ViewBag.AlertMessage = message;
                ViewBag.Uspesno = JsonConvert.DeserializeObject<bool>(HttpContext.Session.GetString("Uspesno"));

                HttpContext.Session.SetString("AlertMessage", "");
            }


            ViewBag.Stavke = stavke;
            ViewBag.Primaoci = primaoci;
            ViewBag.Cene = cene;
            ViewBag.porudzbine = porudzbine;
            return View();
        }


        public IActionResult PreuzmiPorudzbinu(int id)
        {
            Korisnik dostavljac = new Korisnik();

            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UlogovanKorisnik")))
            {
                dostavljac = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("UlogovanKorisnik"));

                if (dostavljac == null)
                {
                    return RedirectToAction("Index", "Authentication");
                }
                else
                {
                    if (dostavljac.TipKorisnika == Tip.ADMINISTRATOR)
                    {
                        return RedirectToAction("Index", "Administrator");
                    }
                    else if (dostavljac.TipKorisnika == Tip.POTROSAC)
                    {
                        return RedirectToAction("Index", "Potrosac");
                    }
                }
            }
            else
            {
                return RedirectToAction("Index", "Authentication");
            }
            ViewBag.korisnik = dostavljac;

            Korpa aktivna = _basketRepository.GetDostavljacActiveBasket(dostavljac.Id);
            if (aktivna != null)
            {
                HttpContext.Session.SetString("AlertMessage", "Dostavljac trenutno dostavlja drugu porudzbinu!");
                HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(false));

                return RedirectToAction("TrenutnaPorudzbina");
            }

            if (!_basketRepository.DostavljacEmpty(id))
            {
                HttpContext.Session.SetString("AlertMessage", "Drugi dostavljac je uzeo ovu porudzbinu pre vas!");
                HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(false));

                return RedirectToAction("NovePorudzbine");
            }

            Korpa korpa = _basketRepository.GetBasketById(id);
            korpa.Status = Status.DostavljaSe;
            korpa.DostavljacId = dostavljac.Id;

            _basketRepository.DostavljacPreuzima(korpa);

            HttpContext.Session.SetString("AlertMessage", "Uspesno ste preuzeli porudzbinu!");
            HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(true));

            return RedirectToAction("TrenutnaPorudzbina");
        }

        public JsonResult Gotovo(string userdata)
        {
            Korpa porudzbina = _basketRepository.GetBasketById(int.Parse(userdata));

            HttpContext.Session.SetString("AlertMessage", "Porudzbina uspesno dostavljena!");
            HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(true));

            porudzbina.Status = Status.Zavrsena;
            _basketRepository.UpdateStatus(porudzbina);

            return Json(1);
        }


        public IActionResult TrenutnaPorudzbina()
        {
            Korisnik dostavljac = new Korisnik();

            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UlogovanKorisnik")))
            {
                dostavljac = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("UlogovanKorisnik"));

                if (dostavljac == null)
                {
                    return RedirectToAction("Index", "Authentication");
                }
                else
                {
                    if (dostavljac.TipKorisnika == Tip.ADMINISTRATOR)
                    {
                        return RedirectToAction("Index", "Administrator");
                    }
                    else if (dostavljac.TipKorisnika == Tip.POTROSAC)
                    {
                        return RedirectToAction("Index", "Potrosac");
                    }
                }
            }
            else
            {
                return RedirectToAction("Index", "Authentication");
            }
            ViewBag.korisnik = dostavljac;

            Korpa porudzbina = _basketRepository.GetDostavljacActiveBasket(dostavljac.Id);

            if(porudzbina == null)
            {

                return View("NemaDostave");
            }

            List<KorpaProizvod> proizvodi = _basketProductRepository.GetAllProducts(porudzbina.Id);

            List<Stavka> stavke = new List<Stavka>();
            foreach (var item in proizvodi)
            {
                Stavka stavka = new Stavka();
                stavka.Proizvod = _productRepository.Get(item.ProizvodId);
                stavka.Kolicina = item.Kolicina;

                stavke.Add(stavka);
            }

            string message = HttpContext.Session.GetString("AlertMessage");
            if (message != "" && message != null)
            {

Web2Project/Views/Dostavljac/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}



<!DOCTYPE html>
<html>
    <head>

    </head>
    <body>
        @if (ViewBag.AlertMessage != null)
        {
            if (ViewBag.Uspesno)
            {
                <script type="text/javascript">
                    window.onload = function () {
                        toastr.success("@ViewBag.AlertMessage");
                    };
                </script>
            }
            else
            {
                <script type="text/javascript">
                    window.onload = function () {
                        toastr.error("@ViewBag.AlertMessage");
                    };
                </script>
            }
        }

        @if (ViewBag.korisnik.Verifikovan == Zahtev.PROCESIRA_SE)
        {
            <label> Vas nalog se jos uvek procesuira, administrator ce obraditi Vas zahtev u najkracem mogucem roku! </label>
        }
        else if (ViewBag.korisnik.Verifikovan == Zahtev.PRIHVACEN)
        {
            <label>@ViewBag.korisnik.KorisnickoIme uspesno ulogovan! </label>
            <label>Vas profil je verifikovan, mozete poceti sa radom!</label>
        }
        else
        {
            <label><font color="Red">Vas nalog je odbijen od strane administratora, ne mozete koristiti usluge naseg sistema!</font></label>
        }
    </body>
</html>

Web2Project/Views/Dostavljac/MojePorudzbine.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Moje porudzbine</title>
    <style>
        #bottom_row_home {
            padding-bottom: 50px;
        }
    </style>
</head>
<body>
    <div class="container row p-0 m-0">
        @if (ViewBag.porudzbine.Count == 0)
        {
            <div class="col-8">
                <h2 class="text-info">U sistemu nema prethodnih porudzbina</h2>
            </div>
        }
        else
        {
            <div>
                <h2 class="text-info">Moje izvrsene dostave</h2>
            </div>
            <div class="row col-12" id="bottom_row_home">

            </div>
            @foreach (var item in ViewBag.porudzbine)
            {
                <div>
                    <h2 class="text-info">Porudzbina @item.Id</h2>
                </div>

                <div class="col-12 border p-3">
                    <table class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr align="center">
                                <th>Naziv proizvoda</th>
                                <th>Kolicina</th>
                                <th>Cena</th>
                                <td></td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var stavka in ViewBag.Stavke)
                            {
                                if (stavka.KorpaId == item.Id)
                                {
                                    <tr align="center">
                                        <td>@stavka.Proizvod.Naziv</td>
                                        <td>@stavka.Kolicina</td>
                                        <td>@stavka.Proizvod.Cena</td>
                                        <td><img src="@stavka.Proizvod.ImagePath" height="100" width="100" asp-append-version="true" /></td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                    <div class="flex">
                        <div class="p-3">
                            <div class="row">
                                <label class="col-7"><strong>Primalac: </strong> @ViewBag.Primaoci[item.Id].KorisnickoIme, @ViewBag.Primaoci[item.Id].Ime @ViewBag.Primaoci[item.Id].Prezime</label> <br />
                                <label class="offset-3">&nbsp;&nbsp;&nbsp;&nbsp;<strong>Cena:</strong> @ViewBag.Cene[item.Id] din</label> <br />
                            </div>
                            <div class="row">
                                <label class="col-7"><strong>Adresa dostave</strong>: @item.AdresaDostave</label> <br />
                                <label class="offset-3"><strong>+ Dostava:</strong> 400 din</label> <br />
                            </div>
                            <div class="row">
                                <label class="col-7"><strong>Komentar</strong>: @item.Komentar</label> <br />
                                <label class="offset-3">&nbsp;&nbsp;&nbsp;&nbsp;<strong>Ukupno: </strong>@item.Cena din</label>
                            </div>
                            <div class="row">
                                <label class="col-7"><strong>Vreme porucivanja</strong>: @item.VremePorucivanja.ToString("dd/MM/yyyy HH:mm")</label> <br />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row col-12" id="bottom_row_home">

                </div>
            }
        }
    </div>
</body>
</html>

Web2Project/Views/Dostavljac/NemaDostave.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<!DOCTYPE html>
<html>
    <head>

    </head>
    <body>
        <div class="col-12">
            <h2 class="text-info">Trenutno ne izvrsavate ni jednu dostavu</h2>
        </div>
    </body>
</html>

Web2Project/Views/Dostavljac/NovePorudzbine.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Aktivne porudzbine</title>
        <style>
        #bottom_row_home {
            padding-bottom: 50px;
        }
    </style>
    </head>
    <body>
        @if (ViewBag.AlertMessage != null)
        {
            if (ViewBag.Uspesno)
            {
                <script type="text/javascript">
                    window.onload = function () {
                        toastr.success("@ViewBag.AlertMessage");
                    };
                </script>
            }
            else
            {
                <script type="text/javascript">
                    window.onload = function () {
                        toastr.error("@ViewBag.AlertMessage");
                    };
                </script>
            }
        }
        <div class="container row p-0 m-0">
            @if (ViewBag.porudzbine.Count == 0)
            {
                <div class="col-7">
                    <h2 class="text-info">Nema aktivnih porudzbina</h2>
                </div>
            }
            else
            {
                <div>
                    <h2 class="text-info">Aktivne porudzbine</h2>
                </div>
                <div class="row col-12" id="bottom_row_home">

                </div>
                @foreach (var item in ViewBag.porudzbine)
                {
                    <div>
                        <h2 class="text-info">Porudzbina @item.Id</h2>
                    </div>

                    <div class="col-12 border p-3">
                        <table class="table table-striped table-bordered" style="width:100%">
                            <thead>
                                <tr align="center">
                                    <th>Naziv proizvoda</th>
                                    <th>Kolicina</th>
                                    <th>Cena</th>
                                    <td></td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var stavka in ViewBag.Stavke)
                                {
                                    if (stavka.KorpaId == item.Id)
                                    {
                                        <tr align="center">
                                            <td>@stavka.Proizvod.Naziv</td>
                                            <td>@stavka.Kolicina</td>
                                            <td>@stavka.Proizvod.Cena</td>
                                            <td><img src="@stavka.Proizvod.ImagePath" height="100" width="100" asp-append-version="true" /></td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                        <div class="flex">
                            <div class="p-3">
                                <div class="row">
                                    <label class="col-7"><strong>Primalac: </strong> @ViewBag.Primaoci[item.Id].KorisnickoIme, @ViewBag.Primaoci[item.Id].Ime @ViewBag.Primaoci[item.Id].Prezime</label> <br />
                                    <label class="offset-3">&nbsp;&nbsp;&nbsp;&nbsp;<strong>Cena:</strong> @ViewBag.Cene[item.Id] din</label> <br />
                                </div>
                                <div class="row">
                                    <label class="col-7"><strong>Kontakt: </strong> @ViewBag.Primaoci[item.Id].Email</label> <br />
                                    <label class="offset-3"><strong>+ Dostava:</strong> 400 din</label> <br />
                                </div>
                                <div class="row">
                                    <label class="col-7"><strong>Adresa dostave</strong>: @item.AdresaDostave</label> <br />
                                    <label class="offset-3">&nbsp;&nbsp;&nbsp;&nbsp;<strong>Ukupno: </strong>@item.Cena din</label>
                                </div>
                                <div class="row">
                                    <label class="col-7"><strong>Komentar</strong>: @item.Komentar</label> <br />
                                </div>
                                <div class="row">
                                    <label class="col-7"><strong>Vreme porucivanja</strong>: @item.VremePorucivanja.ToString("dd/MM/yyyy HH:mm")</label> <br />
                                    <a class="btn btn-info offset-3" href="~/Dostavljac/PreuzmiPorudzbinu?id=@item.Id">Preuzmi porudzbinu</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row col-12" id="bottom_row_home">

                    </div>
                }
            }
        </div>
    </body>
</html>

Web2Project/Views/Dostavljac/TrenutnaPorudzbina.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<!DOCTYPE html>
<html>
<head>
    <script>

        var sekunde;
        var countDownDate;

        function vreme() {

            toastr.success("@ViewBag.AlertMessage");
            $.post("@Url.Action("VratiVreme", "Dostavljac")",
                    {
                        userdata: $("#korpa").val()
                    },
                    function (data) {
                        sekunde = data;
                        countDownDate = new Date().getTime() + sekunde;
                    });
        }

        // Update the count down every 1 second
        var x = setInterval(function () {

            // Get today's date and time
            var now = new Date().getTime();

            // Find the distance between now and the count down date
            var distance = countDownDate - now;

            // Time calculations for days, hours, minutes and seconds
            var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
            var seconds = Math.floor((distance % (1000 * 60)) / 1000);

            // Display the result in the element with id="demo"
            document.getElementById("demo").innerHTML = minutes + "m " + seconds + "s ";

            // If the count down is finished, write some text
            if (distance < 0) {
                clearInterval(x);
                document.getElementById("demo").innerHTML = "";
                $.post("@Url.Action("Gotovo", "Dostavljac")",
                {
                    userdata: $("#korpa").val()
                },
                function (data) {
                    if (data == 1) {
                        location.href = "https://localhost:44364/Dostavljac/NovePorudzbine";
                    }
                });

            }
        }, 1000);
    </script>
</head>
<body onload="vreme()">
    <div class="container row p-0 m-0">
        @if (ViewBag.Korpa == null)
        {
            <div class="col-12">
                <h2 class="text-info">Trenutno ne izvrsavate ni jednu dostavu</h2>
            </div>
        }
        else
        {
            <div class="col-6">
                <h2 class="text-info">Vasa aktivna porudzbina</h2>
            </div>
            <div class="offset-5">
                <label id="demo"></label>
            </div>
            <div class="col-12 border p-3">
                <table class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr align="center">
                            <th>Naziv proizvoda</th>
                            <th>Kolicina</th>
                            <th>Cena</th>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                        @if (ViewBag.Stavke.Count != 0)
                        {
                            foreach (var item in ViewBag.Stavke)
                            {
                                <tr align="center">
                                    <td>@item.Proizvod.Naziv</td>
                                    <td>@item.Kolicina</td>
                                    <td>@item.Proizvod.Cena</td>
                                    <td><img src="@item.Proizvod.ImagePath" height="100" width="100" asp-append-version="true" /></td>
                                </tr>
                            }

                        }
                    </tbody>
                </table>
                <div class="flex">
                    <div class="p-3">
                        <div class="row">
                            <label class="col-7"><strong>Primalac: </strong> @ViewBag.Primalac.KorisnickoIme, @ViewBag.Primalac.Ime @ViewBag.Primalac.Prezime</label> <br />
                            <label class="offset-3">&nbsp;&nbsp;&nbsp;&nbsp;<strong>Cena: </strong>@ViewBag.Cena din</label> <br />
                        </div>
                        <div class="row">
                            <label class="col-7"><strong>Kontakt: </strong> @ViewBag.Primalac.Email</label> <br />
                            <label class="offset-3"><strong>+ Dostava: </strong>400 din</label> <br />
                        </div>
                        <div class="row">
                            <label class="col-7"><strong>Adresa dostave</strong>: @ViewBag.Korpa.AdresaDostave</label> <br />
                            <label class="offset-3">&nbsp;&nbsp;&nbsp;&nbsp;<strong>Ukupno:</strong> @ViewBag.Korpa.Cena din</label>
                        </div>
                        <div class="row">
                            <label class="col-7"><strong>Komentar</strong>: @ViewBag.Korpa.Komentar</label> <br />
                        </div>
                        <div class="row">
                            <label class="col-7"><strong>Vreme porucivanja</strong>: @ViewBag.Korpa.VremePorucivanja.ToString("dd/MM/yyyy HH:mm")</label> <br />
                        </div>
                    </div>
                </div>
            </div>
            <input id="korpa" name="korpa" hidden="hidden" value="@ViewBag.Korpa.Id" />
        }

    </div>
</body>
</html>