Web2Project/Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.Google;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Web2Project.Helper;
using Web2Project.Models;

namespace Web2Project.Controllers
{
    public class AuthenticationController : Controller
    {
        IUserRepository _userRepository;

        public AuthenticationController(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }

        public IActionResult Index()
        {
            Korisnik korisnik = new Korisnik();

            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UlogovanKorisnik")))
            {
                korisnik = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("UlogovanKorisnik"));

                if (korisnik == null)
                {
                    korisnik = new Korisnik();
                }
                else
                {
                    if (korisnik.TipKorisnika == Tip.ADMINISTRATOR)
                    {
                        return RedirectToAction("Index", "Administrator");
                    }
                    else if (korisnik.TipKorisnika == Tip.DOSTAVLJAC)
                    {
                        korisnik.Verifikovan = _userRepository.VratiZahtev(korisnik.Id);
                        HttpContext.Session.SetString("UlogovanKorisnik", JsonConvert.SerializeObject(korisnik));

                        return RedirectToAction("Index", "Dostavljac");
                    }
                    else
                    {
                        return RedirectToAction("Index", "Potrosac");
                    }
                } 
            }

            string message = HttpContext.Session.GetString("AlertMessage");
            if (message != "" && message != null)
            {
                ViewBag.AlertMessage = message;
                ViewBag.Uspesno = JsonConvert.DeserializeObject<bool>(HttpContext.Session.GetString("Uspesno"));

                HttpContext.Session.SetString("AlertMessage", "");
            }

            

            ViewBag.Ime = "";
            ViewBag.Message = "";

            ViewBag.korisnik = korisnik;
            return View();
        }

        [HttpPost]
        public IActionResult Login(string korisnickoIme, string lozinka)
        {
            if (korisnickoIme == "" || korisnickoIme == null || lozinka == "" || lozinka == null)
            {
                HttpContext.Session.SetString("AlertMessage", "Sva polja moraju biti popunjena");
                HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(false));

                return RedirectToAction("Index");
            }

            if (!_userRepository.Existing(korisnickoIme))
            {
                HttpContext.Session.SetString("AlertMessage", "Ovo korisnicko ime ne postoji");
                HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(false));

                return RedirectToAction("Index");
            }

            lozinka = Operations.hashPassword(lozinka);
            Korisnik korisnik = _userRepository.Get(korisnickoIme);

            if(korisnik.Lozinka != lozinka)
            {
                ViewBag.Ime = korisnickoIme;
                ViewBag.korisnik = new Korisnik();
                ViewBag.Message = "Pogresna lozinka";

                return View("Index");
            }

            korisnik.LogIn();
            HttpContext.Session.SetString("UlogovanKorisnik", JsonConvert.SerializeObject(korisnik));
            

            HttpContext.Session.SetString("AlertMessage", ("Korisnik " + korisnickoIme + " uspesno ulogovan!"));
            HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(true));

            if (korisnik.TipKorisnika == Tip.ADMINISTRATOR)
            {
                return RedirectToAction("Index", "Administrator");
            }
            else if (korisnik.TipKorisnika == Tip.DOSTAVLJAC)
            {
                return RedirectToAction("Index", "Dostavljac");
            }
            return RedirectToAction("Index", "Potrosac");            
        }

        public IActionResult Logout()
        {
            Korisnik korisnik = new Korisnik();

            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UlogovanKorisnik")))
            {
                korisnik = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("UlogovanKorisnik"));

                if (korisnik == null)
                {
                    return RedirectToAction("Index", "Authentication");
                }
            }
            else
            {
                return RedirectToAction("Index", "Authentication");
            }

            korisnik.LogOut();
            HttpContext.SignOutAsync();

            HttpContext.Session.SetString("UlogovanKorisnik", JsonConvert.SerializeObject(null));

            HttpContext.Session.SetString("AlertMessage", ("Korisnik " + korisnik.KorisnickoIme + " uspesno odjavljen!"));
            HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(true));
            return RedirectToAction("Index");
        }

        public async Task LogInGoogle()
        {
            await HttpContext.ChallengeAsync(GoogleDefaults.AuthenticationScheme, new AuthenticationProperties()
            {
                RedirectUri = Url.Action("GoogleResponse")
            });
        }

        public IActionResult DopuniPodatke()
        {
            ViewBag.korisnik = new Korisnik();
            return View();
        }

        [HttpPost]
        public IActionResult PodaciDopunjeni(string Adresa, DateTime DatumRodjenja)
        {
            if(Adresa == "")
            {
                HttpContext.Session.SetString("AlertMessage", "Sva polja moraju biti popunjena!");
                HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(false));

                return RedirectToAction("Index");
            }

            Korisnik korisnik = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("PrivremeniKorisnik"));

            korisnik.Adresa = Adresa;
            korisnik.DatumRodjenja = DatumRodjenja;
            korisnik.LogedIn = true;

            _userRepository.Add(korisnik);

            HttpContext.Session.SetString("UlogovanKorisnik", JsonConvert.SerializeObject(korisnik));

            HttpContext.Session.SetString("AlertMessage", "Korisnik uspesno registrovan!");
            HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(true));

            return RedirectToAction("Index", "Potrosac");
        }


        public async Task<IActionResult> GoogleResponse()
        {
            var result = await HttpContext.AuthenticateAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            var claims = result.Principal.Identities
                .FirstOrDefault().Claims.Select(claim => new
                {
                    claim.Issuer,
                    claim.OriginalIssuer,
                    claim.Type,
                    claim.Value
                });

            string korisnickoIme = claims.FirstOrDefault().Value;

            Korisnik korisnikSaEmail = _userRepository.GetKorisnikWithSameEmail(claims.Where(e => e.Type.Contains("emailaddress")).FirstOrDefault().Value);

            if(korisnikSaEmail != null)
            {
                korisnikSaEmail.LogedIn = true;

                HttpContext.Session.SetString("UlogovanKorisnik", JsonConvert.SerializeObject(korisnikSaEmail));

                return RedirectToAction("Index", "Potrosac");
            }

            Korisnik korisnik = _userRepository.Get(korisnickoIme);

            if (korisnik == null)
            {
                korisnik = new Korisnik();
                korisnik.KorisnickoIme = korisnickoIme;
                korisnik.Ime = claims.Where(e => e.Type.Contains("givenname")).FirstOrDefault().Value;
                korisnik.Prezime = claims.Where(e => e.Type.Contains("surname")).FirstOrDefault().Value;
                korisnik.Email = claims.Where(e => e.Type.Contains("emailaddress")).FirstOrDefault().Value;
                korisnik.TipKorisnika = Tip.POTROSAC;
                korisnik.Verifikovan = Zahtev.PRIHVACEN;
                korisnik.ImagePath = claims.Where(e => e.Type.Contains("picture")).FirstOrDefault().Value;
                korisnik.Google = true;

                HttpContext.Session.SetString("PrivremeniKorisnik", JsonConvert.SerializeObject(korisnik));

                return RedirectToAction("DopuniPodatke");
            }

            korisnik.LogedIn = true;
            HttpContext.Session.SetString("UlogovanKorisnik", JsonConvert.SerializeObject(korisnik));

            return RedirectToAction("Index", "Potrosac");
        }
    }
}

Web2Project/Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.IO;
using System.Text.RegularExpressions;
using Web2Project.Helper;
using Web2Project.Models;
using Web2Project.Services;

namespace Web2Project.Controllers
{
    public class RegistrationController : Controller
    {
        IUserRepository _userRepository;
        IFileUploadService _fileUploadService;
        IEmailSender _emailSender;

        public RegistrationController(IUserRepository userRepository, IFileUploadService fileUploadService, IEmailSender emailSender)
        {
            _userRepository = userRepository;
            _fileUploadService = fileUploadService;
            _emailSender = emailSender;

        }

        public IActionResult Index()
        {
            Korisnik korisnik = new Korisnik();

            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("UlogovanKorisnik")))
            {
                korisnik = JsonConvert.DeserializeObject<Korisnik>(HttpContext.Session.GetString("UlogovanKorisnik"));

                if (korisnik == null)
                {
                    korisnik = new Korisnik();
                }
                else
                {
                    if (korisnik.TipKorisnika == Tip.ADMINISTRATOR)
                    {
                        return RedirectToAction("Index", "Administrator");
                    }
                    else if (korisnik.TipKorisnika == Tip.DOSTAVLJAC)
                    {
                        return RedirectToAction("Index", "Dostavljac");
                    }
                    else
                    {
                        return RedirectToAction("Index", "Potrosac");
                    }
                }
            }

            string message = HttpContext.Session.GetString("AlertMessage");
            if (message != "" && message != null)
            {
                ViewBag.AlertMessage = message;
                ViewBag.Uspesno = JsonConvert.DeserializeObject<bool>(HttpContext.Session.GetString("Uspesno"));

                HttpContext.Session.SetString("AlertMessage", "");
            }

            ViewBag.korisnik = korisnik;
            ViewBag.Message = "";

            return View();
        }
        
        public JsonResult CheckUserAvailability(string userdata)
        {
            if (_userRepository.Existing(userdata))
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }

        public JsonResult EmailValidation(string email)
        {
            bool isEmail = Regex.IsMatch(email, @"\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z", RegexOptions.IgnoreCase);

            if (isEmail)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }

        [HttpPost]
        public ActionResult Add(Korisnik korisnik, string ponovoLozinka, IFormFile ifile)
        {
            if (korisnik.KorisnickoIme == null || korisnik.KorisnickoIme == "" || korisnik.Ime == null || korisnik.Ime == "" || korisnik.Prezime == null || korisnik.Prezime == "" || korisnik.Lozinka == null || korisnik.Lozinka == "" || korisnik.Email == null || korisnik.Email == "" || korisnik.DatumRodjenja > DateTime.Now)
            {
                HttpContext.Session.SetString("AlertMessage", "Sva polja moraju biti popunjena");
                HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(false));

                return RedirectToAction("Index");
            }

            if (_userRepository.Existing(korisnik.KorisnickoIme))
            {
                HttpContext.Session.SetString("AlertMessage", "Korisnicko ime je zauzeto");
                HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(false));

                return RedirectToAction("Index");
            }

            if(korisnik.Lozinka != ponovoLozinka)
            {
                HttpContext.Session.SetString("AlertMessage", "Lozinke se ne poklapaju!");
                HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(false));

                return RedirectToAction("Index");
            }

            if(ifile != null)
            {
                string imgext = Path.GetExtension(ifile.FileName).ToLower();
                if (imgext != ".jpg" && imgext != ".png")
                {
                    HttpContext.Session.SetString("AlertMessage", "Slika mora biti u .jpg ili .png formatu!");
                    HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(false));

                    return RedirectToAction("Index");
                }
            }

            bool isEmail = Regex.IsMatch(korisnik.Email, @"\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z", RegexOptions.IgnoreCase);
            if (isEmail)
            {
                if (korisnik.TipKorisnika == Tip.POTROSAC)
                {
                    korisnik.Verifikovan = Zahtev.PRIHVACEN;

                    Message message = new Message(new string[] { "markoprodanovic96@gmail.com" }, "[Web 2] - Projekat", "Uspesno ste se registrovali na sistem, mozete koristiti usluge naseg sistema!");
                    _emailSender.SendEmail(message);

                    HttpContext.Session.SetString("AlertMessage", "Korisnik uspesno registrovan!");
                    HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(true));
                }
                else
                {
                    korisnik.Verifikovan = Zahtev.PROCESIRA_SE;

                    Message message = new Message(new string[] { "markoprodanovic96@gmail.com" }, "[Web 2] - Projekat", "Vas nalog se procesuira, administrator ce obraditi vas zahtev u najkracem mogucem roku!");
                    _emailSender.SendEmail(message);

                    HttpContext.Session.SetString("AlertMessage", "Korisnik uspesno registrovan, ceka se verifikacija od strane administratora!");
                    HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(true));
                }

                korisnik.Lozinka = Operations.hashPassword(korisnik.Lozinka);
              
                _userRepository.Add(korisnik);

                string imagePath = "";

                if (ifile != null)
                {
                    _fileUploadService.UploadFile(ifile, korisnik.Id.ToString(), "Korisnici");
                    imagePath = "~/Korisnici/" + korisnik.Id + ".jpg";
                }
                else
                {
                    imagePath = "~/Korisnici/unknown.jpg";
                }

                _userRepository.UpdateKorisnik(korisnik, "ImagePath", imagePath);

                
                return RedirectToAction("Index", "Authentication");
            }
            else
            {
                HttpContext.Session.SetString("AlertMessage", "Email nije validan");
                HttpContext.Session.SetString("Uspesno", JsonConvert.SerializeObject(false));

                return RedirectToAction("Index");
            }
        }
    }
}

Web2Project/Views/Authentication/DopuniPodatke.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Dovrsi registraciju</title>
    <script>
            function AdresaEmpty() {
                if ($("#Adresa").val() == "") {
                    $("#Status1").html('<font color="Red">Ovo polje mora biti popunjano!</font>');
                    $("#Adresa").css("border-color", "Red");
                } else {
                    $("#Status1").html('');
                    $("#Adresa").css("border-color", "lightgray");
                }
            }

            function vratiDatum() {
                var today = new Date();
                var dd = today.getDate();
                var mm = today.getMonth() + 1;
                var yyyy = today.getFullYear();

                if (dd < 10) {
                    dd = '0' + dd;
                }

                if (mm < 10) {
                    mm = '0' + mm;
                }

                today = yyyy + '-' + mm + '-' + dd;
                document.getElementById("DatumRodjenja").setAttribute("max", today);
            }

            function validateForm() {
                var dobro = true;
                if ($("#Adresa").val() == "") {
                    $("#Status1").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                    $("#Adresa").css("border-color", "Red");
                    dobro = false;
                }else {
                    $("#Status1").html('');
                    $("#Adresa").css("border-color", "lightgray");
                }
                if ($("#DatumRodjenja").val() == "") {
                    $("#Status2").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                    $("#DatumRodjenja").css("border-color", "Red");
                    dobro = false;
                }else {
                    $("#Status2").html('');
                    $("#DatumRodjenja").css("border-color", "lightgray");
                }
                return dobro;
            }
    </script>
    <style>
        p.tekstic {
            color: grey;
        }
        div.row {
            display: flex;
            align-items: center;
        }
    </style>
</head>
<body onload="javascript:vratiDatum()">
    <h2 class="text-info">Dovrsite registraciju</h2>
    <br />
    <form method="post" action="~/Authentication/PodaciDopunjeni" onsubmit="return validateForm()">
        <div class="form-group">
            <div class="row">
                <label class="control-label col-sm-2">Unesite adresu:</label>
                <div class="col-sm-3">
                    <input class="form-control" type="text" onchange="AdresaEmpty()" placeholder="Unesite adresu stanovnja" maxlength="70" id="Adresa" name="Adresa" />
                </div>
                <label class="col-sm-4" id="Status1"></label>
            </div>
            <div class="row">
                <label class="col-sm-2"></label>
                <div class="col-sm-4">
                    <p class="tekstic"><i>U formatu adresa i broj, grad, postanski broj</i></p>
                </div>
            </div>
            <br />
            <div class="row">
                <label class="control-label col-sm-2">Datum rodjenja:</label>
                <div class="col-sm-3">
                    <input class="form-control" type="date" id="DatumRodjenja" min='1899-01-01' name="DatumRodjenja" />
                </div>
                <label class="col-sm-4" id="Status2"></label>
            </div>
            <br />
            <div class="row">
                <div class="col-sm-4">
                    <input class="btn btn-primary" type="submit" value="Dovrsi registraciju" />
                </div>
            </div>
        </div>
    </form>
</body>
</html>

Web2Project/Views/Authentication/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Log in or sign up</title>
    <style>
        div.row {
            display: flex;
            align-items: center;
        }
    </style>
    <script>

            var username = true;

            function UserNameCheck() {
                if ($("#korisnickoIme").val() == "") {

                    $("#Status1").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                    $("#korisnickoIme").css("border-color", "Red");

                }else{
                    $.post("@Url.Action("CheckUserAvailability", "Registration")",
                    {
                        userdata: $("#korisnickoIme").val()
                    },
                    function (data) {
                        if (data == 0) {

                            $("#Status1").html('<font color="Red">Ovo korisnicko ime ne postoji!</font>');
                            $("#korisnickoIme").css("border-color", "Red");
                            username = false;
                        } else {

                            $("#Status1").html('');
                            $("#korisnickoIme").css("border-color", "lightgray");
                            username = true;
                        }
                    });
                }
            }

            function PasswordCheck() {
                if ($("#lozinka").val() == "") {

                    $("#Status2").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                    $("#lozinka").css("border-color", "Red");

                } else {
                    $("#Status2").html('');
                    $("#lozinka").css("border-color", "lightgray");
                }
            }

            function validateForm() {

                var dobro = true;

                if ($("#korisnickoIme").val() == "") {
                    $("#Status1").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                    $("#korisnickoIme").css("border-color", "Red");
                    dobro = false;
                } else if (username) {
                    $("#Status1").html('');
                    $("#korisnickoIme").css("border-color", "lightgray");
                }
                if ($("#lozinka").val() == "") {
                    $("#Status2").html('<font color="Red">Ovo polje mora biti popunjeno!</font>');
                    $("#lozinka").css("border-color", "Red");
                    dobro = false;
                } else {
                    $("#Status2").html('');
                    $("#lozinka").css("border-color", "lightgray");
                }

                return (dobro && username);
            }
    </script>
</head>
<body>
    @if (ViewBag.AlertMessage != null)
    {
        if (ViewBag.Uspesno)
        {
            <script type="text/javascript">
                    window.onload = function () {
                        toastr.success("@ViewBag.AlertMessage");
                    };
            </script>
        }
        else
        {
            <script type="text/javascript">
                    window.onload = function () {
                        toastr.error("@ViewBag.AlertMessage");
                    };
            </script>
        }
    }
    <div class="row">
        <div class="col-sm-10"></div>
        <a class="btn btn-success col-sm-2" asp-controller="Registration" asp-action="Index">Registruj se</a>
    </div>
    <br />
    <h2 class="text-info">Ulogujte se:</h2>
    <br />
    <form method="post" action="~/Authentication/Login" onsubmit="return validateForm()">
        <div class="form-group">
            <div class="row">
                <label class="control-label col-sm-2">Korisnicko ime:</label>
                <div class="col-sm-3">
                    <input class="form-control" type="text" value="@ViewBag.Ime" onchange="UserNameCheck()" maxlength="30" placeholder="Unesite korisnicko ime" id="korisnickoIme" name="korisnickoIme" />
                </div>
                <label class="col-sm-4" id="Status1"></label>
            </div>
            <br />
            <div class="row">
                <label class="control-label col-sm-2">Lozinka:</label>
                <div class="col-sm-3">
                    <input class="form-control" type="password" onchange="PasswordCheck()" maxlength="30" placeholder="Unesite lozinku" id="lozinka" name="lozinka" />
                </div>
                <label class="col-sm-4" id="Status2"><font color="Red">@ViewBag.Message</font></label>
            </div>
            <br />
            <div class="row">
                <div class="col-sm-4">
                    <input class="btn btn-primary" type="submit" value="Uloguj se" />
                </div>
                <div class="col-sm-4">
                    <a class="btn btn-outline-danger" asp-controller="Authentication" asp-action="LogInGoogle">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-google" viewBox="0 0 16 16">
                            <path d="M15.545 6.558a9.42 9.42 0 0 1 .139 1.626c0 2.434-.87 4.492-2.384 5.885h.002C11.978 15.292 10.158 16 8 16A8 8 0 1 1 8 0a7.689 7.689 0 0 1 5.352 2.082l-2.284 2.284A4.347 4.347 0 0 0 8 3.166c-2.087 0-3.86 1.408-4.492 3.304a4.792 4.792 0 0 0 0 3.063h.003c.635 1.893 2.405 3.301 4.492 3.301 1.078 0 2.004-.276 2.722-.764h-.003a3.702 3.702 0 0 0 1.599-2.431H8v-3.08h7.545z" />
                        </svg>
                        Sign in with Google
                    </a>
                </div>
            </div>
        </div>
    </form>
</body>
</html>